name: reproducing_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  package_one:
    git:
      url: https://github.com/rafaeltab/dart-pub-repro.git
      path: packages/package_one
      tag_pattern: "v{{version}}"
    version: 1.0.5

flutter:
  uses-material-design: true
