name: reproducing_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.4

some_git: &some_git https://github.com/rafaeltab/dart-pub-repro.git

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  package_one:
    git:
      url: *some_git
      tag_pattern: v{{version}}
      path: packages/package_one
    version: 1.0.4

flutter:
  uses-material-design: true
